"""
Build Kaggle submission.py

Usage
-----
python build_submission.py

Output
------
submission.py
"""

from pathlib import Path
import re

ROOT = Path(".")

MODULES = [
    "state.py",
    "board.py",
    "actions.py",
    "economy.py",
    "market.py",
    "scheduler.py",
    "search.py",
    "planner.py",
    "agent.py",
]

OUTPUT = ROOT / "submission.py"


HEADER = """\
# ==========================================================
# AUTO GENERATED FILE
# Generated by build_submission.py
# Do not edit manually.
# ==========================================================

"""

internal_modules = {
    Path(m).stem
    for m in MODULES
}


def clean_source(text):

    lines = []

    imports = []

    body = []

    for line in text.splitlines():

        if line.startswith("from "):

            m = re.match(
                r"from\s+([a-zA-Z0-9_]+)\s+import",
                line,
            )

            if m:

                mod = m.group(1)

                if mod in internal_modules:
                    continue

            imports.append(line)

            continue

        if line.startswith("import "):

            imports.append(line)

            continue

        body.append(line)

    return imports, body


all_imports = []

all_body = []

seen = set()

for module in MODULES:

    path = ROOT / module

    text = path.read_text()

    imports, body = clean_source(text)

    for imp in imports:

        if imp not in seen:

            seen.add(imp)

            all_imports.append(imp)

    all_body.append(
        f"\n# ===================== {module} =====================\n"
    )

    all_body.extend(body)

with OUTPUT.open("w") as f:

    f.write(HEADER)

    for imp in sorted(all_imports):

        f.write(imp + "\n")

    f.write("\n")

    for line in all_body:

        f.write(line + "\n")

print("Created:", OUTPUT)
